on:
  push:
    branches:
      - main
  # Run this once per day
  schedule:
    - cron: '37 1 * * *'
  workflow_dispatch:

name: Retweet

jobs:
  retweet:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: retweet

      - name: Retweet
        run: |
          Rscript ./script.R

          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          # detect changes (the code is derived from https://stackoverflow.com/a/3879077)
          git add secrets/
          git update-index --refresh
          if ! git diff-index --quiet HEAD -- secrets/; then
            # Overwrite the existing commit
            git commit --amend -m "Update secrets [skip ci]"
            git push origin --force-with-lease main
          else
            echo "No changes"
          fi
        env:
          RSTATS_JA_BOT_KEY: ${{ secrets.RSTATS_JA_BOT_KEY }}
